# Generated by Django 5.1.4 on 2025-01-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('core_ranking', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coauthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coauthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthored_with', to='api.researcher')),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthors', to='api.researcher')),
            ],
        ),
    ]
