# Generated by Django 5.1.4 on 2024-12-15 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('papers', models.IntegerField(default=0)),
                ('h_index', models.IntegerField(default=0)),
                ('citations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stars', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='api.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('core_ranking', models.CharField(blank=True, max_length=10, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('citations', models.IntegerField(default=0)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='api.researcher')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='api.researcher')),
            ],
        ),
    ]
